import Head from 'next/head';
import Main from '../components/Main';
import { StyledMain } from '../components/styled';

export default function Home() {
  return (
    // <div className={styles.container}>
    <>
      <Head>
        <title>Who's taller?</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <StyledMain>
      <Main />
      </StyledMain>
      </>
    // </div>
  );
}
